# Example configurations for different deployment scenarios

# Basic development deployment
basic:
  config:
    karmaUrl: "http://karma.default.svc.cluster.local:8080"
    logLevel: "DEBUG"

# Production deployment with ingress and scaling
production:
  replicaCount: 2
  
  config:
    karmaUrl: "http://karma.monitoring.svc.cluster.local:8080"
    logLevel: "INFO"
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/rate-limit: "100"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: karma-mcp.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: karma-mcp-tls
        hosts:
          - karma-mcp.example.com
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

# High availability deployment
ha:
  replicaCount: 3
  
  config:
    karmaUrl: "http://karma.monitoring.svc.cluster.local:8080"
    logLevel: "WARNING"
  
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - karma-mcp
            topologyKey: kubernetes.io/hostname
  
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "fast-ssd"

# Development with persistent storage
development:
  config:
    karmaUrl: "http://karma.default.svc.cluster.local:8080"
    logLevel: "DEBUG"
  
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Minimal resource deployment
minimal:
  config:
    karmaUrl: "http://karma:8080"
    logLevel: "INFO"
  
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  
  healthCheck:
    initialDelaySeconds: 60
    periodSeconds: 60