apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karma-mcp.fullname" . }}
  labels:
    {{- include "karma-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "karma-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karma-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args: ["echo 'MCP Server for Karma deployed - tools available for Claude integration' && python -c 'import sys; sys.path.append(\"/app/src\"); from karma_mcp.server import check_karma; import asyncio; print(asyncio.run(check_karma())); import time; time.sleep(3600)'"]
          env:
            - name: KARMA_URL
              value: {{ .Values.config.karmaUrl | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - |
                  import sys; sys.path.append('/app/src')
                  from karma_mcp.server import check_karma
                  import asyncio
                  result = asyncio.run(check_karma())
                  sys.exit(0 if result.get('status') == 'ok' else 1)
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - |
                  import sys; sys.path.append('/app/src')
                  from karma_mcp.server import check_karma
                  import asyncio
                  result = asyncio.run(check_karma())
                  sys.exit(0 if result.get('status') == 'ok' else 1)
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}